### ISSUE TITLE
Issue with prestashop 1.6 Instamojo new API

### ISSUE THREAD

**Issue by husein522** [Instamojo/Instamojo-PrestaShop#17]
Hi,
I installed new version of API. when I click on confirm . I get error as 504 Gateway Time-out

The server didn't respond in time.

Plz find attached

![capture](https://cloud.githubusercontent.com/assets/14772523/26247186/5871e39a-3cba-11e7-8d4e-f58f1ca97a55.JPG)

**Comment by ashwch** [comment]
@husein522 Is it still happening? Were you using test credentials or production?

**Comment by husein522** [comment]
Hi,
Now its working fine

Thanks
