### ISSUE TITLE
Payment Gateway Authorization Failed.

### ISSUE THREAD

**Issue by ramp4578** [Instamojo/Instamojo-PrestaShop#18]
Hello,

I used **https://test.instamojo.com** credentials in the module.

There is no input field to keep Private Salt. Check the attachment for the my configuration.
![modules nayna studios](https://cloud.githubusercontent.com/assets/23413746/26311839/44fd75a2-3f23-11e7-960f-4d564f5bb93e.png)

My Shop URL: **http://naynastudios.com/new1**

I am getting the error called "Payment Gateway Authorization Failed."

Can you provide some solution for my problem?

**Comment by ashwch** [comment]
Please go through https://support.instamojo.com/hc/en-us/articles/212214265-How-do-I-get-my-Client-ID-and-Client-Secret-
