### ISSUE TITLE
Subject Line of Payment Conf Email sent to Payer

### ISSUE THREAD

**Issue by zuii81** [Instamojo/Instamojo-PrestaShop#20]
While testing this module in sandbox, I see that the payer gets this email "You have paid for 'Instapay' on Instamojo"

This is not a shopping-friendly email subject. Can this be changed in anyway?

**Comment by ashwch** [comment]
This is not a plugin specific issue, more of an API decision. I think you have already sent us an email regarding this hence I will be closing the issue here.
