### ISSUE TITLE
Installation error in 1.6.1.4

### ISSUE THREAD

**Issue by sudhin-joseph** [Instamojo/Instamojo-PrestaShop#9]
Module not installed properly error displayed.

The module configuration tab is active and we can enter API key and other data but payment method is not active in checkout page.
![screenshot from 2016-06-20 17 29 49](https://cloud.githubusercontent.com/assets/16698621/16193483/0980bcf6-370d-11e6-938e-eb90825810d0.png)

**Comment by ashwch** [comment]
@sudhin-origami Automatic installation has been fixed in the latest release.
